import { describe, expect, test } from "bun:test"
import fs from "fs"
import path from "path"
import os from "os"
import { RunDirectory } from "../../src/cli/run-directory"

describe("RunDirectory.resolveRunDirectory", () => {
  test("mints a fresh isolated engagement directory when no --dir and not resuming", () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-run-dir-"))
    const resolved = RunDirectory.resolveRunDirectory(undefined, cwd)
    expect(resolved).not.toBe(cwd)
    expect(fs.existsSync(resolved)).toBe(true)
  })

  test("falls back to the launch cwd when resuming (--continue/--session) with no --dir", () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-run-dir-"))
    const resolved = RunDirectory.resolveRunDirectory(undefined, cwd, { preferCwd: true })
    expect(resolved).toBe(cwd)
  })

  test("an explicit --dir wins over resuming", () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-run-dir-"))
    const explicit = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-run-dir-explicit-"))
    const resolved = RunDirectory.resolveRunDirectory(explicit, cwd, { preferCwd: true })
    expect(resolved).toBe(explicit)
  })
})

describe("RunDirectory.isAutoGeneratedEngagementDirectory", () => {
  test("recognizes a freshly-minted default engagement workspace", () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-run-dir-"))
    const minted = RunDirectory.resolveRunDirectory(undefined, cwd)
    expect(RunDirectory.isAutoGeneratedEngagementDirectory(minted)).toBe(true)
  })

  test("does not flag an explicit project directory", () => {
    const explicit = fs.mkdtempSync(path.join(os.tmpdir(), "impactr-real-project-"))
    expect(RunDirectory.isAutoGeneratedEngagementDirectory(explicit)).toBe(false)
  })
})
