export * as RunDirectory from "./run-directory"

import fs from "fs"
import path from "path"
import { ulid } from "ulid"
import { Global } from "@impactr-ai/core/global"

function readPackageName(dir: string): string | undefined {
  try {
    const raw = fs.readFileSync(path.join(dir, "package.json"), "utf8")
    return (JSON.parse(raw) as { name?: string }).name
  } catch {
    return undefined
  }
}

// Detects Impactr's own dev checkout, so an engagement workspace can never resolve inside it.
export function isInsideImpactrSource(directory: string): boolean {
  let dir = path.resolve(directory)
  for (let i = 0; i < 64; i++) {
    if (readPackageName(dir) === "impactr") return true
    // Also catches siblings of the impactr/ app dir, e.g. the outer git root, .agents/.
    if (readPackageName(path.join(dir, "impactr")) === "impactr") return true
    const parent = path.dirname(dir)
    if (parent === dir) return false
    dir = parent
  }
  return false
}

const engagementsRoot = path.join(Global.Path.data, "engagements")

// True for a directory this module minted itself (~/.local/share/impactr/engagements/<ulid>), as
// opposed to a real project checkout the operator pointed at explicitly via --dir. Auto-generated
// workspaces are per-launch and carry no stable identity of their own, so callers that dedupe local
// engagement records by directory (EngagementStore.findReusable) should not treat two different
// auto-generated paths as "different projects" — only an explicit --dir is a meaningful boundary.
export function isAutoGeneratedEngagementDirectory(directory: string): boolean {
  const resolved = path.resolve(directory)
  return resolved === engagementsRoot || resolved.startsWith(engagementsRoot + path.sep)
}

let cachedDefault: string | undefined

// Cached so the `directory:` cmd option and the run handler's own chdir agree on one path.
function defaultEngagementDirectory(): string {
  if (cachedDefault) return cachedDefault
  const dir = path.join(engagementsRoot, ulid())
  fs.mkdirSync(dir, { recursive: true })
  // A run that aborts before ever using it would otherwise leave an empty folder behind forever.
  process.on("exit", () => {
    try {
      if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir)
    } catch {}
  })
  cachedDefault = dir
  return dir
}

function assertSafeDirectory(resolved: string, allowUnsafeDir?: boolean) {
  if (allowUnsafeDir || !isInsideImpactrSource(resolved)) return
  console.error(
    `Refusing to run against ${resolved} — it's inside Impactr's own source tree.\n` +
      `Point --dir at an isolated engagement workspace instead, or pass --allow-unsafe-dir to override.`,
  )
  process.exit(1)
}

// preferCwd (--continue/--session) uses the launch directory, since that's where a resumed session lives.
export function resolveRunDirectory(
  dir: string | undefined,
  cwd: string,
  options?: { allowUnsafeDir?: boolean; preferCwd?: boolean },
): string {
  if (!dir) {
    if (!options?.preferCwd) return defaultEngagementDirectory()
    const resolved = path.resolve(cwd)
    assertSafeDirectory(resolved, options?.allowUnsafeDir)
    return resolved
  }
  const resolved = path.isAbsolute(dir) ? dir : path.resolve(cwd, dir)
  assertSafeDirectory(resolved, options?.allowUnsafeDir)
  return resolved
}
